### ISSUE TITLE
Make deploy CLI illustrate errors in Adama file rather than a mysterious error code

### ISSUE THREAD

**Issue by mathgladiator** [mathgladiator/adama-lang#104]
Given bad code

validating plan...
compiling plan...
Exception in thread "main" org.adamalang.common.ErrorCodeException: code:117823
    at org.adamalang.runtime.deploy.DeploymentFactory.compile(DeploymentFactory.java:87)
    at org.adamalang.runtime.deploy.DeploymentFactory.<init>(DeploymentFactory.java:62)
    at org.adamalang.cli.commands.Space.spaceDeploy(Space.java:141)
    at org.adamalang.cli.commands.Space.execute(Space.java:42)
    at org.adamalang.cli.Main.main(Main.java:62)

This is not useful. We shouldn't crash, but instead should pretty print some useful debugging information.

**Comment by mathgladiator** [comment]
```
java -jar adama.jar code compile-file --file ../chat.adama --dump-to chat.java
Parsing exception:Parser was expecting a Symbol=`;`; instead, the parse got Symbol:}. {Token: `}` @ (34,0) -> (34,1): Symbol}
File failed to compile
```

```
java -jar adama.jar code compile-file --file ../chat.adama --dump-to chat.java
[start=33:2, end=33:5] :Type check failure: the type 'int' is unable to store type 'list<void>'. (TypeCheckReferences)
File failed to compile
```
