### ISSUE TITLE
Production: Tracking down a threading issue

### ISSUE THREAD

**Issue by mathgladiator** [mathgladiator/adama-lang#176]
```
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at org.adamalang.runtime.sys.LivingDocument.__buildBroadcastList(LivingDocument.java:484)
        at org.adamalang.runtime.sys.LivingDocument.__invalidate_trailer(LivingDocument.java:313)
        at org.adamalang.runtime.sys.LivingDocument.__transaction_invalidate_body(LivingDocument.java:1673)
        at org.adamalang.runtime.sys.LivingDocument.__transact(LivingDocument.java:1136)
        at org.adamalang.runtime.sys.DurableLivingDocument.executeNow(DurableLivingDocument.java:533)
        at org.adamalang.runtime.sys.DurableLivingDocument.finishSuccessDataServicePatchWhileInExecutor(DurableLivingDocument.java:373)
        at org.adamalang.runtime.sys.DurableLivingDocument.executeNow(DurableLivingDocument.java:517)
        at org.adamalang.runtime.sys.DurableLivingDocument.ingest(DurableLivingDocument.java:715)
        at org.adamalang.runtime.sys.DurableLivingDocument.load(DurableLivingDocument.java:750)
        at org.adamalang.runtime.sys.DurableLivingDocument$2.success(DurableLivingDocument.java:182)
        at org.adamalang.runtime.sys.DurableLivingDocument$2.success(DurableLivingDocument.java:172)
        at org.adamalang.caravan.CaravanDataService.lambda$get$2(CaravanDataService.java:323)
        at org.adamalang.caravan.CaravanDataService$6.execute(CaravanDataService.java:262)
        at org.adamalang.common.NamedRunnable.run(NamedRunnable.java:36)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mathgladiator** [comment]
Here is what is bizarre about this.. The document is from load, so it is isolated....
